services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    ports:
      - "3005:3000"  # Map to a different host port
    env_file:
      - ./api/.env
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    environment:
      - PORT=5173
      - VITE_API_URL=http://localhost:3005  # Point to mapped port
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge