services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    expose:
      - "3000"    # Not "3000:3000" - expose doesn't use port mapping syntax
    env_file:
      - ./api/.env
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    environment:
      - PORT=5173
      - VITE_API_URL=http://backend:3000  # Point to backend service
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge