services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    ports:
      - "3005:3000"  # Map to a different host port
    env_file:
      - ./api/.env
    networks:
      - app-network
    environment:
      - TZ=America/Los_Angeles

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    environment:
      - PORT=5173
      - VITE_API_URL=https://semantle-backend.qwertea.dev  # Point to mapped port
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge